#!/bin/sh
# shellcheck disable=SC2016  # literal $ and backticks are intentional
# One-shot init: reads .env, validates it, and writes
#   - the Blocky config (upstreams from .env + static blocky.yml)
#   - the Traefik dynamic config (routers, auth, rate limit, Cloudflare allowlist)
# then exits. Nothing internet-facing ever gets write access to Traefik's config.
#
# Values are read straight from the .env file rather than the container
# environment, so Docker Compose never gets a chance to interpolate the `$`
# signs in the bcrypt hash.
set -eu

ENV_FILE="${ENV_FILE:-/env-file}"
TEMPLATE="${TEMPLATE:-/blocky-template.yml}"
BLOCKY_OUT="${BLOCKY_OUT:-/blocky/config.yml}"
TRAEFIK_OUT="${TRAEFIK_OUT:-/traefik-dynamic/doh-auth.yml}"

fail() { echo "| CONFIG-INIT: ERROR — $*" >&2; exit 1; }
matches() { printf '%s' "$1" | grep -Eq "$2"; }

# Last assignment wins, like dotenv. Strips CR, surrounding quotes, and `\$`
# escapes pasted from shell-escaped settings.
get() {
  v=$(grep "^$1=" "$ENV_FILE" 2>/dev/null | tail -n 1 | cut -d= -f2- | tr -d '\r') || true
  v=$(printf '%s' "$v" | sed "s/^['\"]//;s/['\"]\$//;s/\\\\\\$/\$/g")
  printf '%s' "${v:-$2}"
}

[ -r "$ENV_FILE" ] || fail "env file $ENV_FILE not readable"

DOMAIN=$(get DOMAIN "")
SUBDOMAIN=$(get DOH_SUBDOMAIN resolver)
SECRET_PATH=$(get DOH_SECRET_PATH "")
DOH_USER=$(get DOH_USER "")
DOH_HASH=$(get DOH_HASHED_PASS "")
NEXTDNS_ID=$(get NEXTDNS_ID "")
FALLBACKS=$(get FALLBACK_UPSTREAMS "https://cloudflare-dns.com/dns-query,https://dns.quad9.net/dns-query")
CF_PROXY=$(get CLOUDFLARE_PROXY false)
ENTRYPOINT=$(get TRAEFIK_ENTRYPOINT websecure)
CERT_RESOLVER=$(get TRAEFIK_CERT_RESOLVER letsencrypt)

# --- Validation. Everything below ends up inside YAML, so reject anything
# outside a conservative character set instead of trying to escape it.
matches "$DOMAIN" '^[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+$' || fail "DOMAIN must be an apex domain like example.com (got '$DOMAIN')"
matches "$SUBDOMAIN" '^[A-Za-z0-9-]+$' || fail "DOH_SUBDOMAIN must be a single label like 'resolver'"
matches "$ENTRYPOINT" '^[A-Za-z0-9_-]+$' || fail "TRAEFIK_ENTRYPOINT is invalid"
matches "$CERT_RESOLVER" '^[A-Za-z0-9_-]+$' || fail "TRAEFIK_CERT_RESOLVER is invalid"
case "$CF_PROXY" in true|false) ;; *) fail "CLOUDFLARE_PROXY must be true or false" ;; esac

if [ -n "$SECRET_PATH" ]; then
  matches "$SECRET_PATH" '^[A-Za-z0-9_-]{24,}$' || fail "DOH_SECRET_PATH must be 24+ chars of [A-Za-z0-9_-] (use: openssl rand -hex 24)"
fi
if [ -n "$DOH_USER$DOH_HASH" ]; then
  matches "$DOH_USER" '^[A-Za-z0-9._-]+$' || fail "DOH_USER must be set and use only [A-Za-z0-9._-]"
  matches "$DOH_HASH" '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$' || fail "DOH_HASHED_PASS must be a bcrypt hash from: htpasswd -nbB user password"
fi
[ -n "$SECRET_PATH" ] || [ -n "$DOH_HASH" ] || fail "set DOH_SECRET_PATH, DOH_USER + DOH_HASHED_PASS, or both — refusing to run an open resolver"

UPSTREAMS=""
if [ -n "$NEXTDNS_ID" ]; then
  matches "$NEXTDNS_ID" '^[A-Za-z0-9]+$' || fail "NEXTDNS_ID must be the short ID from your NextDNS dashboard (e.g. abc123)"
  UPSTREAMS="https://dns.nextdns.io/$NEXTDNS_ID"
else
  echo "| CONFIG-INIT: WARNING — NEXTDNS_ID not set, using fallback upstreams only"
fi
for u in $(printf '%s' "$FALLBACKS" | tr ',' ' '); do
  matches "$u" '^(https://|tcp-tls:|quic:)[A-Za-z0-9.:/_-]+$' || fail "FALLBACK_UPSTREAMS entry '$u' is invalid"
  UPSTREAMS="$UPSTREAMS $u"
done
[ -n "$UPSTREAMS" ] || fail "no upstreams configured"

HOST="$SUBDOMAIN.$DOMAIN"

# --- Blocky config
{
  echo "# Generated by config-init.sh on every deploy — edit blocky.yml or .env instead."
  echo "upstreams:"
  echo "  strategy: strict   # ask upstreams in order; the next one only if the previous fails"
  echo "  timeout: 2s"
  echo "  init:"
  echo "    strategy: fast"
  echo "  groups:"
  echo "    default:"
  for u in $UPSTREAMS; do echo "      - \"$u\""; done
  echo
  cat "$TEMPLATE"
} > "$BLOCKY_OUT.tmp"
mv "$BLOCKY_OUT.tmp" "$BLOCKY_OUT"

# --- Traefik dynamic config
chain() {
  # Allowlist first: the rate limit trusts CF-Connecting-IP only after it.
  [ "$CF_PROXY" = true ] && printf '        - private-doh-cloudflare-only\n'
  printf '        - private-doh-ratelimit\n'
  printf '        - %s\n' "$1"
}
router() { # name rule priority final-middleware
  cat <<EOF
    $1:
      rule: "Host(\`$HOST\`) && $2"
      entryPoints:
        - $ENTRYPOINT
      service: private-doh
      priority: $3
      tls:
        certResolver: $CERT_RESOLVER
      middlewares:
EOF
  chain "$4"
}

{
  echo "# Generated by config-init.sh (Dokploy-Private-DoH) on every deploy. Do not edit."
  echo "http:"
  echo "  routers:"
  [ -n "$SECRET_PATH" ] && router private-doh-secret-path "Path(\`/dns-query/$SECRET_PATH\`)" 210 private-doh-strip-secret
  [ -n "$DOH_HASH" ] && router private-doh-basic-auth "PathPrefix(\`/dns-query\`)" 200 private-doh-basic-auth
  cat <<EOF
  services:
    private-doh:
      loadBalancer:
        servers:
          - url: "http://private-doh-blocky:4000"
  middlewares:
    private-doh-ratelimit:
      rateLimit:
        # Per client IP. Generous because one page load can fire dozens of lookups.
        average: 50
        burst: 200
EOF
  if [ "$CF_PROXY" = true ]; then
    # Only safe because the allowlist below guarantees the request came from Cloudflare.
    printf '        sourceCriterion:\n          requestHeaderName: CF-Connecting-IP\n'
    # ponytail: hard-coded from https://www.cloudflare.com/ips/ (2026-09); refresh if Cloudflare adds ranges.
    cat <<EOF
    private-doh-cloudflare-only:
      ipAllowList:
        sourceRange:
          - 173.245.48.0/20
          - 103.21.244.0/22
          - 103.22.200.0/22
          - 103.31.4.0/22
          - 141.101.64.0/18
          - 108.162.192.0/18
          - 190.93.240.0/20
          - 188.114.96.0/20
          - 197.234.240.0/22
          - 198.41.128.0/17
          - 162.158.0.0/15
          - 104.16.0.0/13
          - 104.24.0.0/14
          - 172.64.0.0/13
          - 131.0.72.0/22
          - 2400:cb00::/32
          - 2606:4700::/32
          - 2803:f800::/32
          - 2405:b500::/32
          - 2405:8100::/32
          - 2a06:98c0::/29
          - 2c0f:f248::/32
EOF
  fi
  if [ -n "$SECRET_PATH" ]; then
    printf '    private-doh-strip-secret:\n      replacePath:\n        path: /dns-query\n'
  fi
  if [ -n "$DOH_HASH" ]; then
    printf '    private-doh-basic-auth:\n      basicAuth:\n        users:\n'
    printf '          - "%s:%s"\n' "$DOH_USER" "$DOH_HASH"
  fi
} > "$TRAEFIK_OUT.tmp"
mv "$TRAEFIK_OUT.tmp" "$TRAEFIK_OUT"

echo "| CONFIG-INIT: https://$HOST/dns-query — secret path: $([ -n "$SECRET_PATH" ] && echo on || echo off), basic auth: $([ -n "$DOH_HASH" ] && echo "on ($DOH_USER)" || echo off), cloudflare-only: $CF_PROXY"
echo "| CONFIG-INIT: upstreams (in order):$UPSTREAMS"
